/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab9p2_equipo7_alejandrocardona_carlosmoncada;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JTextField;


/**
 *
 * @author jets
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        listDB();
        PB.setStringPainted(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelAgregar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Order = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Ship = new javax.swing.JTextField();
        Segment = new javax.swing.JTextField();
        State = new javax.swing.JTextField();
        ProductID = new javax.swing.JTextField();
        ProductName = new javax.swing.JTextField();
        Sales = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Discount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        OrderDate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CustomerID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Country = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        PostalCode = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Category = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ShipDate = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        CustomerName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Region = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Sub_Category = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Profit = new javax.swing.JTextField();
        PanelList = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_Listar = new javax.swing.JTextArea();
        PanelElim = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Elim = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        PB = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Order ID:");

        jLabel2.setText("Ship Mode:");

        jLabel3.setText("Segment: ");

        jLabel4.setText("State:");

        jLabel5.setText("Product ID");

        jLabel6.setText("Product Name:");

        jLabel7.setText("Sales:");

        jLabel8.setText("Quantity:");

        jLabel9.setText("Discount");

        jButton1.setText("Agregar Registro");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel10.setText("Order Date:");

        jLabel11.setText("Customer ID:");

        jLabel12.setText("Country:");

        jLabel13.setText("Postal Code:");

        jLabel14.setText("Category:");

        jLabel15.setText("Ship Date:");

        jLabel16.setText("Customer Name:");

        jLabel17.setText("City: ");

        jLabel18.setText("Region:");

        jLabel19.setText("Sub-Category");

        jLabel20.setText("Profit");

        javax.swing.GroupLayout PanelAgregarLayout = new javax.swing.GroupLayout(PanelAgregar);
        PanelAgregar.setLayout(PanelAgregarLayout);
        PanelAgregarLayout.setHorizontalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgregarLayout.createSequentialGroup()
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelAgregarLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(27, 27, 27)
                                        .addComponent(Sales, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Order, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Ship)
                                                    .addComponent(Segment)
                                                    .addComponent(State)))
                                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(ProductID)))))
                                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(Profit))
                                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(18, 18, 18)
                                                .addComponent(Category))
                                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addComponent(PostalCode))
                                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(Country))
                                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(CustomerID))
                                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(OrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(161, 161, 161)
                                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ShipDate))
                                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CustomerName))
                                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(City))
                                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addGap(18, 18, 18)
                                                .addComponent(Region))
                                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(18, 18, 18)
                                                .addComponent(Sub_Category))))))
                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        PanelAgregarLayout.setVerticalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(OrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(ShipDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Ship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Segment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(PostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(Region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(Sub_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Sales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(Profit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Agregar Registro", PanelAgregar);

        jButton2.setText("Orders");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Details");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Customers");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Products");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Clear");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        TA_Listar.setColumns(20);
        TA_Listar.setRows(5);
        jScrollPane1.setViewportView(TA_Listar);

        javax.swing.GroupLayout PanelListLayout = new javax.swing.GroupLayout(PanelList);
        PanelList.setLayout(PanelListLayout);
        PanelListLayout.setHorizontalGroup(
            PanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(PanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(PanelListLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(82, 82, 82)
                        .addComponent(jButton3)
                        .addGap(86, 86, 86)
                        .addComponent(jButton4)
                        .addGap(76, 76, 76)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE)
                        .addComponent(jButton6)))
                .addGap(101, 101, 101))
        );
        PanelListLayout.setVerticalGroup(
            PanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(PanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar Registros", PanelList);

        Table_Elim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Row ID", "Order ID", "Order Date", "Customer ID", "Country", "City", "Product ID", "Sales"
            }
        ));
        jScrollPane2.setViewportView(Table_Elim);

        jButton7.setText("Update Table");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
        });

        jButton8.setText("Eliminar Registro");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelElimLayout = new javax.swing.GroupLayout(PanelElim);
        PanelElim.setLayout(PanelElimLayout);
        PanelElimLayout.setHorizontalGroup(
            PanelElimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelElimLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelElimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelElimLayout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        PanelElimLayout.setVerticalGroup(
            PanelElimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelElimLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(PanelElimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Registro", PanelElim);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PB, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        ArrayList<JTextField> tfs = new ArrayList();
        
        UIManager.put("nimbusOrange", Color.yellow);
        
        
        
        String orderid=Order.getText();
        tfs.add(Order);
        String shipmode=Ship.getText();
        tfs.add(Ship);
        String segment=Segment.getText();
        tfs.add(Segment);
        String state=State.getText();
        tfs.add(State);
        String productoid=ProductID.getText();
        tfs.add(ProductID);
        String productname=ProductName.getText();
        tfs.add(ProductName);
        String sales=Sales.getText();
        tfs.add(Sales);
        String cuantity=Quantity.getText();
        tfs.add(Quantity);
        String discount=Discount.getText();
        tfs.add(Discount);
        String profit=Profit.getText();
        tfs.add(Profit);
        String orderdate=OrderDate.getText();
        tfs.add(OrderDate);
        String costumerid=CustomerID.getText();
        tfs.add(CustomerID);
        String country=Country.getText();
        tfs.add(Country);
        String postalcode=PostalCode.getText();
        tfs.add(PostalCode);
        String category=Category.getText();
        tfs.add(Category);
        String shipdate=ShipDate.getText();
        tfs.add(ShipDate);
        String customername=CustomerName.getText();
        tfs.add(CustomerName);
        String city=City.getText();
        tfs.add(City);
        String region=Region.getText();
        tfs.add(Region);
        String subcategory=Sub_Category.getText();
        tfs.add(Sub_Category);

        Agregar a = new Agregar(orderid, orderdate, shipdate, shipmode, costumerid, customername, segment, country, city, state, postalcode, region, productoid, category, subcategory, productname, sales, cuantity, discount, profit);
        AdministradorPB apb = new AdministradorPB(300, PB,true,tfs);
        System.out.println("");
        apb.start();
        apb.setMessage("Se ha agregado a la base de datos de manera exitosa");
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
        UIManager.put("nimbusOrange", Color.green);
        
        
        
        Dba db = new Dba("./Nilaccdb.accdb");
        db.conectar();
        try {
            db.query.execute("select [Order ID],[Order Date],[Ship Date],[Ship Mode],[Customer ID] from TenRecord");
            ResultSet rs = db.query.getResultSet();
            String salida = "";
            while (rs.next()) {
                String orderid = rs.getString(1);
                String OrderDate = rs.getString(2);
                String Shipdate = rs.getString(3);
                String shipMode = rs.getString(4);
                String costumerid = rs.getString(5);
                salida += "\tRecord:" + orderid + "\n";
                salida += "\tOrder id:" + OrderDate + "\n";
                salida += "\tOrderDate:" + Shipdate + "\n";
                salida += "\tshipMode:" + shipMode + "\n";
                salida += "\tcostumerid:" + costumerid + "\n\n\n";

            }
            
            
            AdministradorPB apb = new AdministradorPB(200, PB, true, TA_Listar,salida);
            apb.setMessage("Se ha listado la base de datos de manera exitosa");
            apb.start();
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
        UIManager.put("nimbusOrange", Color.orange);
        
        
        Dba db = new Dba("./Nilaccdb.accdb");
        db.conectar();
        try {
            db.query.execute("select  [Order ID], [Product ID], Sales, Quantity, Discount, Profit from TenRecord");
            ResultSet rs = db.query.getResultSet();
            String salida = "";
            while (rs.next()) {
                String orderid = rs.getString(1);
                String productid = rs.getString(2);
                String sales = rs.getString(3);
                String quantity = rs.getString(4);
                String discount = rs.getString(5);

                salida += "\tRegistro:" + orderid + "\n";
                salida += "\tproductid:" + productid + "\n";
                salida += "\tsales:" + sales + "\n";
                salida += "\tquantity:" + quantity + "\n";
                salida += "\tdiscount:" + discount + "\n\n\n";

            }
            AdministradorPB apb = new AdministradorPB(250, PB, true, TA_Listar,salida);
            apb.setMessage("Se ha listado la base de datos de manera exitosa");
            apb.start();
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        
UIManager.put("nimbusOrange", Color.red);
        
        
        
        
        Dba db = new Dba("./Nilaccdb.accdb");
        db.conectar();
        try {
            
            String acum = "";
            db.query.execute("select Id,[Customer ID],[Customer Name],Country,City,State,[Postal Code],Region FROM TenRecord");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                String ID = rs.getString(1);
                String RowID = rs.getString(2);
                String OrderID = rs.getString(3);
                String orderDate = rs.getString(4);
                String customerID = rs.getString(5);
                String country = rs.getString(6);
                String city = rs.getString(7);
                String productID = rs.getString(8);
                acum+="Registro "+ID+"  \n "+RowID+" \n"+OrderID+"\n "+orderDate+" \n"+customerID+"\n "+country+" \n"+city+" \n"+productID+"\n\n\n";
                
            }
            AdministradorPB apb = new AdministradorPB(200, PB, true, TA_Listar,acum);
            apb.setMessage("Se ha listado la base de datos de manera exitosa");
            apb.start();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        
        
        
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        
        UIManager.put("nimbusOrange", Color.blue);
        
        Dba db = new Dba("./Nilaccdb.accdb");
        db.conectar();
        try {
            
            String acum = "";
            db.query.execute("select Id,[Product ID],Category,[Sub-Category],[Product Name],Sales,Quantity,Discount,Profit FROM TenRecord");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                String ID = rs.getString(1);
                String RowID = rs.getString(2);
                String OrderID = rs.getString(3);
                String orderDate = rs.getString(4);
                String customerID = rs.getString(5);
                String country = rs.getString(6);
                String city = rs.getString(7);
                String productID = rs.getString(8);
                String profit = rs.getString(9);
                acum+="Registro "+ID+"  \n "+RowID+"\n "+OrderID+" \n "+orderDate+" "+customerID+"\n "+country+"\n "+city+" \n"+productID+" \n"+profit+"\n\n\n";
                
            }
            AdministradorPB apb = new AdministradorPB(200, PB, true, TA_Listar,acum);
            apb.setMessage("Se ha listado la base de datos de manera exitosa");
            apb.start();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel modelo = (DefaultTableModel) Table_Elim.getModel();
        int x =modelo.getRowCount();
        for(int i = 0; i<x; i++){
            
            modelo.removeRow(0);
            
        }
        Table_Elim.setModel(modelo);
        listDB();
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        
        delDB();
        
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        
        TA_Listar.setText("");
        JOptionPane.showMessageDialog(this, "Se ha limpiado correctamente");
        
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }
    private void listDB(){
        DefaultTableModel modelo = (DefaultTableModel) Table_Elim.getModel();
        
        
        Dba db = new Dba("./Nilaccdb.accdb");
        db.conectar();
        try {
            
            
            db.query.execute("select Id, [Order ID], [Order Date], [Customer ID],Country,City,[Product ID],Sales from TenRecord");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                String RowID = rs.getString(1);
                String OrderID = rs.getString(2);
                String orderDate = rs.getString(3);
                String customerID = rs.getString(4);
                String country = rs.getString(5);
                String city = rs.getString(6);
                String productID = rs.getString(7);
                String sales = rs.getString(8);
                Object [] arreglo = {RowID, OrderID, orderDate, customerID, country, city, productID, sales};
                modelo.addRow(arreglo);
                
            }
            Table_Elim.setModel(modelo);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        
    }
    private void delDB(){
        
        Dba db = new Dba("./Nilaccdb.accdb");
        db.conectar();
        int selElim = Integer.parseInt((String)Table_Elim.getValueAt(Table_Elim.getSelectedRow(), 0));
        try {
            db.query.execute("delete from TenRecord where Id="+selElim);
            db.commit();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Category;
    private javax.swing.JTextField City;
    private javax.swing.JTextField Country;
    private javax.swing.JTextField CustomerID;
    private javax.swing.JTextField CustomerName;
    private javax.swing.JTextField Discount;
    private javax.swing.JTextField Order;
    private javax.swing.JTextField OrderDate;
    private javax.swing.JProgressBar PB;
    private javax.swing.JPanel PanelAgregar;
    private javax.swing.JPanel PanelElim;
    private javax.swing.JPanel PanelList;
    private javax.swing.JTextField PostalCode;
    private javax.swing.JTextField ProductID;
    private javax.swing.JTextField ProductName;
    private javax.swing.JTextField Profit;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField Region;
    private javax.swing.JTextField Sales;
    private javax.swing.JTextField Segment;
    private javax.swing.JTextField Ship;
    private javax.swing.JTextField ShipDate;
    private javax.swing.JTextField State;
    private javax.swing.JTextField Sub_Category;
    private javax.swing.JTextArea TA_Listar;
    private javax.swing.JTable Table_Elim;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
